name: jobfinder_ui
description:  widgets,colors.themes.
publish_to: none
version: 1.0.0
environment: 
  sdk: ^3.0.6
  flutter: ^3.10.6
  
dependencies: 
  flutter: 
    sdk: flutter
  flutter_svg: ^1.1.6

# dev_dependencies: 
#   flutter_test: 
#     sdk: flutter
# flutter: 
#   uses-material-design: true
  # assets: 
  #   - assets/
  #   - assets/images/
  # fonts: 
  #   - family: DM Sans
  #     fonts: 
  #       - asset: assets/fonts/DMSansBold.ttf
  #         weight: 700
  #       - asset: assets/fonts/DMSansRegular.ttf
  #         weight: 400
  #   - family: Open Sans
  #     fonts: 
  #       - asset: assets/fonts/OpenSansRomanSemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/OpenSansRomanRegular.ttf
  #         weight: 400
  #       - asset: assets/fonts/OpenSansRomanBold.ttf
  #         weight: 700
